name:                tennis-hs
version:             0.1.0.0
license:             OtherLicense
maintainer:          "j@florius.com.ar"
copyright:           "2021 Joaquin Azcarate"

default-extensions:
  - OverloadedStrings

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  tennis-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tennis-hs

tests:
  tennis-hs-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tennis-hs
    - hspec
    - QuickCheck
